In [1]:
print('Anand')

Anand


In [2]:
print('Gina')

Gina


In [3]:
import math
math.sqrt(100)

10.0

In [4]:
math.sqrt(10000)

100.0

In [5]:
'anand'.title()

'Anand'

In [6]:
'anand'.upper()

'ANAND'

In [7]:
'gina'.upper()

'GINA'

In [10]:
dir(str)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',


In [8]:
import numpy as np
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [11]:
name ='anand raj'
name.title()

'Anand Raj'

In [14]:
b = np.arange(100)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [15]:
np.median(b)

49.5

In [ ]:
np.mendian()

In [19]:
def get_first_item(a):
    return a[0]

In [20]:
get_first_item([1,2,3])

1

In [21]:
def get_name(first_name, last_name):
    return f'{first_name.title()} {last_name.title()}'
get_name('gina', 'edwards')

'Gina Edwards'

In [22]:
get_name(last_name='edwards', first_name='gina')

'Gina Edwards'

In [24]:
fn_list = ['gina', 'anand']
ln_list = ['edwards', 'rag']

In [26]:
def get_names(fn_list, ln_list):
    names = []
    for i in range(len(fn_list)):
        full_name = fn_list[i].title() + ' ' + ln_list[i].title()
        names.append(full_name)
    return names
get_names(fn_list, ln_list)        

['Gina Edwards', 'Anand Rag']

In [27]:
import seaborn as sns
df = sns.load_dataset('tips')
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [29]:
df['exp_tip'] = 0.15*df.total_bill
df.head()

total_bill   tip     sex smoker  day    time  size  exp_tip
0       16.99  1.01  Female     No  Sun  Dinner     2   2.5485
1       10.34  1.66    Male     No  Sun  Dinner     3   1.5510
2       21.01  3.50    Male     No  Sun  Dinner     3   3.1515
3       23.68  3.31    Male     No  Sun  Dinner     2   3.5520
4       24.59  3.61  Female     No  Sun  Dinner     4   3.6885

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
 7   exp_tip     244 non-null    float64 
dtypes: category(4), float64(3), int64(1)
memory usage: 9.3 KB


In [32]:
df['name'] = df.smoker.astype(str) + ' ' + df.day.astype(str)
df.head()

total_bill   tip     sex smoker  day    time  size  exp_tip    name
0       16.99  1.01  Female     No  Sun  Dinner     2   2.5485  No Sun
1       10.34  1.66    Male     No  Sun  Dinner     3   1.5510  No Sun
2       21.01  3.50    Male     No  Sun  Dinner     3   3.1515  No Sun
3       23.68  3.31    Male     No  Sun  Dinner     2   3.5520  No Sun
4       24.59  3.61  Female     No  Sun  Dinner     4   3.6885  No Sun

In [40]:
import numpy as np
df.groupby('sex', as_index=False).agg({'total_bill':'mean', 'tip':'sum'})

sex  total_bill     tip
0    Male   20.744076  485.07
1  Female   18.056897  246.51

In [34]:
df1 = df[['sex', 'total_bill']]
df1

sex  total_bill
0    Female       16.99
1      Male       10.34
2      Male       21.01
3      Male       23.68
4    Female       24.59
..      ...         ...
239    Male       29.03
240  Female       27.18
241    Male       22.67
242    Male       17.82
243  Female       18.78

[244 rows x 2 columns]

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
 7   exp_tip     244 non-null    float64 
 8   name        244 non-null    object  
dtypes: category(4), float64(3), int64(1), object(1)
memory usage: 11.2+ KB


In [50]:
df = sns.load_dataset('titanic')
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [55]:
df[df.age.isna()]

survived  pclass     sex  age  sibsp  parch     fare embarked   class  \
5           0       3    male  NaN      0      0   8.4583        Q   Third   
17          1       2    male  NaN      0      0  13.0000        S  Second   
19          1       3  female  NaN      0      0   7.2250        C   Third   
26          0       3    male  NaN      0      0   7.2250        C   Third   
28          1       3  female  NaN      0      0   7.8792        Q   Third   
..        ...     ...     ...  ...    ...    ...      ...      ...     ...   
859         0       3    male  NaN      0      0   7.2292        C   Third   
863         0       3  female  NaN      8      2  69.5500        S   Third   
868         0       3    male  NaN      0      0   9.5000        S   Third   
878         0       3    male  NaN      0      0   7.8958        S   Third   
888         0       3  female  NaN      1      2  23.4500        S   Third   

       who  adult_male deck  embark_town alive  alone  age_clean  
5      man        True  NaN   Queenstown    no   True  29.699118  
17     man        True  NaN  Southampton   yes   True  29.699118  
19   woman       False  NaN    Cherbourg   yes   True  29.699118  
26     man        True  NaN    Cherbourg    no   True  29.699118  
28   woman       False  NaN   Queenstown   yes   True  29.699118  
..     ...         ...  ...          ...   ...    ...        ...  
859    man        True  NaN    Cherbourg    no   True  29.699118  
863  woman       False  NaN  Southampton    no  False  29.699118  
868    man        True  NaN  Southampton    no   True  29.699118  
878    man        True  NaN  Southampton    no   True  29.699118  
888  woman       False  NaN  Southampton    no  False  29.699118  

[177 rows x 16 columns]

In [59]:
df.mean()

/var/folders/5w/ddnm7z315b3_md0ryj55swx80000gs/T/ipykernel_18887/3698961737.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.mean()


survived       0.383838
pclass         2.308642
age           29.699118
sibsp          0.523008
parch          0.381594
fare          32.204208
adult_male     0.602694
alone          0.602694
age_clean     29.699118
dtype: float64

In [58]:
df1 = df.fillna(df.mean())
df1.head(10)

/var/folders/5w/ddnm7z315b3_md0ryj55swx80000gs/T/ipykernel_18887/1308331074.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df1 = df.fillna(df.mean())


survived  pclass     sex        age  sibsp  parch     fare embarked  \
0         0       3    male  22.000000      1      0   7.2500        S   
1         1       1  female  38.000000      1      0  71.2833        C   
2         1       3  female  26.000000      0      0   7.9250        S   
3         1       1  female  35.000000      1      0  53.1000        S   
4         0       3    male  35.000000      0      0   8.0500        S   
5         0       3    male  29.699118      0      0   8.4583        Q   
6         0       1    male  54.000000      0      0  51.8625        S   
7         0       3    male   2.000000      3      1  21.0750        S   
8         1       3  female  27.000000      0      2  11.1333        S   
9         1       2  female  14.000000      1      0  30.0708        C   

    class    who  adult_male deck  embark_town alive  alone  age_clean  
0   Third    man        True  NaN  Southampton    no  False  22.000000  
1   First  woman       False    C    Cherbourg   yes  False  38.000000  
2   Third  woman       False  NaN  Southampton   yes   True  26.000000  
3   First  woman       False    C  Southampton   yes  False  35.000000  
4   Third    man        True  NaN  Southampton    no   True  35.000000  
5   Third    man        True  NaN   Queenstown    no   True  29.699118  
6   First    man        True    E  Southampton    no   True  54.000000  
7   Third  child       False  NaN  Southampton    no  False   2.000000  
8   Third  woman       False  NaN  Southampton   yes  False  27.000000  
9  Second  child       False  NaN    Cherbourg   yes  False  14.000000

In [54]:
df['age'] = df['age'].fillna(df.age.mean())
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
 15  age_clean    891 non-null    float64 
dtypes: bool(2), category(2), float64(3), int64(4), object(5)
memory usage: 87.6+ KB


In [52]:
df.fillna('mean')

ValueError: Cannot setitem on a Categorical with a new category, set the categories first